-- =====================================================================
-- Gimnasio: esquema y datos de ejemplo (PostgreSQL 13 o superior)
-- Guía «Agentes de IA y bases de datos», Laboratorio de Bases de Datos
--
-- Uso:
--   createdb -U postgres gimnasio
--   psql -U postgres -d gimnasio -f gimnasio.sql
--
-- El esquema reproduce, a propósito, algunas decisiones de diseño
-- discutibles, que se analizan en el capítulo 6 (revisión del modelo).
-- Todos los datos personales son ficticios.
-- =====================================================================

DROP TABLE IF EXISTS pagos_clientes, jornadas_laborales, titulos, reciben, clases,
    areas, es_jefe, entrenadores, clientes, personas CASCADE;

CREATE TABLE personas (
    id_persona       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre           VARCHAR(100) NOT NULL,
    apellido         VARCHAR(100) NOT NULL,
    dni              VARCHAR(10)  NOT NULL,
    fecha_nacimiento DATE         NOT NULL,
    email            VARCHAR(100) NOT NULL UNIQUE,
    direccion        VARCHAR(200) NOT NULL,
    fecha_inicio     DATE         NOT NULL,
    fecha_fin        DATE
);

CREATE TABLE clientes (
    id_cliente  INTEGER     NOT NULL PRIMARY KEY,
    plan        VARCHAR(10) NOT NULL CHECK (plan IN ('BASICO', 'ESTANDAR', 'PREMIUM')),
    CONSTRAINT fk_clientes_personas FOREIGN KEY (id_cliente) REFERENCES personas (id_persona)
);

CREATE TABLE entrenadores (
    id_entrenador INTEGER     NOT NULL PRIMARY KEY,
    modalidad     VARCHAR(10) NOT NULL CHECK (modalidad IN ('PERSONAL', 'GENERAL')),
    CONSTRAINT fk_entrenadores_personas FOREIGN KEY (id_entrenador) REFERENCES personas (id_persona)
);

CREATE TABLE es_jefe (
    id_entrenador INTEGER NOT NULL PRIMARY KEY,
    jefe          INTEGER NOT NULL,
    CONSTRAINT fk_es_jefe_entrenador FOREIGN KEY (id_entrenador) REFERENCES personas (id_persona),
    CONSTRAINT fk_es_jefe_jefe FOREIGN KEY (jefe) REFERENCES personas (id_persona)
);

CREATE TABLE areas (
    id_area INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre  VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE clases (
    id_clase   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo       VARCHAR(45) NOT NULL,
    dia        VARCHAR(10) NOT NULL CHECK (dia IN ('LUNES', 'MARTES', 'MIERCOLES', 'JUEVES', 'VIERNES')),
    horario    TIME        NOT NULL,
    area       INTEGER     NOT NULL,
    entrenador INTEGER     NOT NULL,
    CONSTRAINT fk_clases_areas FOREIGN KEY (area) REFERENCES areas (id_area),
    CONSTRAINT fk_clases_entrenadores FOREIGN KEY (entrenador) REFERENCES entrenadores (id_entrenador),
    CONSTRAINT uq_clases UNIQUE (tipo, dia, horario, entrenador)
);

CREATE TABLE reciben (
    id_reciben INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    clase      INTEGER NOT NULL,
    cliente    INTEGER NOT NULL,
    CONSTRAINT fk_reciben_clases FOREIGN KEY (clase) REFERENCES clases (id_clase),
    CONSTRAINT fk_reciben_clientes FOREIGN KEY (cliente) REFERENCES clientes (id_cliente),
    CONSTRAINT uq_reciben UNIQUE (clase, cliente)
);

CREATE TABLE titulos (
    id_titulo  INTEGER     NOT NULL,
    tipo       VARCHAR(45) NOT NULL,
    entrenador INTEGER     NOT NULL,
    CONSTRAINT fk_titulos_entrenadores FOREIGN KEY (entrenador) REFERENCES entrenadores (id_entrenador)
);
CREATE UNIQUE INDEX ck_titulos ON titulos (tipo, entrenador);

CREATE TABLE jornadas_laborales (
    id_jornada  INTEGER     NOT NULL,
    dia         VARCHAR(10) NOT NULL CHECK (dia IN ('LUNES', 'MARTES', 'MIERCOLES', 'JUEVES', 'VIERNES')),
    hora_inicio TIME        NOT NULL,
    hora_fin    TIME        NOT NULL,
    empleado    INTEGER     NOT NULL,
    CONSTRAINT fk_jornadas_personas FOREIGN KEY (empleado) REFERENCES personas (id_persona)
);

CREATE TABLE pagos_clientes (
    id_pago INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha   DATE         NOT NULL,
    monto   NUMERIC(8,2) NOT NULL DEFAULT 0,
    cliente INTEGER      NOT NULL,
    CONSTRAINT fk_pagos_clientes FOREIGN KEY (cliente) REFERENCES clientes (id_cliente)
);

-- ---------------------------------------------------------------------
-- Datos (ficticios)
-- ---------------------------------------------------------------------

INSERT INTO personas (id_persona, nombre, apellido, dni, fecha_nacimiento, email, direccion, fecha_inicio, fecha_fin) VALUES
    (1,  'Lucía',    'Ferreyra',  '40111222', DATE '1997-04-12', 'lferreyra@correo.test',  'Belgrano 120',     DATE '2024-02-01', NULL),
    (2,  'Martín',   'Quiroga',   '38222333', DATE '1994-09-30', 'mquiroga@correo.test',   'Saavedra 455',     DATE '2023-08-15', NULL),
    (3,  'Carla',    'Benítez',   '42333444', DATE '2000-01-22', 'cbenitez@correo.test',   'Moreno 78',        DATE '2025-03-10', NULL),
    (4,  'Diego',    'Salinas',   '36444555', DATE '1991-06-05', 'dsalinas@correo.test',   'Alem 1020',        DATE '2022-11-01', NULL),
    (5,  'Paula',    'Ríos',      '41555666', DATE '1998-12-17', 'prios@correo.test',      'Sarmiento 300',    DATE '2024-06-20', NULL),
    (6,  'Tomás',    'Acosta',    '43666777', DATE '2001-03-03', 'tacosta@correo.test',    'Italia 88',        DATE '2025-01-05', NULL),
    (7,  'Julieta',  'Méndez',    '39777888', DATE '1995-07-28', 'jmendez@correo.test',    'España 640',       DATE '2023-04-18', NULL),
    (8,  'Nicolás',  'Paz',       '44888999', DATE '2002-10-09', 'npaz@correo.test',       'Francia 210',      DATE '2025-07-01', NULL),
    (9,  'Sofía',    'Gutiérrez', '37999000', DATE '1993-02-14', 'sgutierrez@correo.test', 'Roca 505',         DATE '2021-09-09', NULL),
    (10, 'Agustín',  'Molina',    '40111222', DATE '1997-05-02', 'amolina@correo.test',    'Pellegrini 33',    DATE '2024-10-10', NULL),
    (11, 'Valentina','Castro',    '45123456', DATE '2003-08-21', 'vcastro@correo.test',    'Mitre 999',        DATE '2025-02-14', NULL),
    (12, 'Federico', 'Rojas',     '35234567', DATE '1990-11-11', 'frojas@correo.test',     'Rivadavia 2100',   DATE '2020-05-05', NULL),
    (13, 'Camila',   'Ortiz',     '38345678', DATE '1994-01-30', 'cortiz@correo.test',     'Lavalle 17',       DATE '2022-03-01', NULL),
    (14, 'Ignacio',  'Vega',      '36456789', DATE '1992-04-04', 'ivega@correo.test',      'Urquiza 402',      DATE '2021-01-15', NULL),
    (15, 'Florencia','Luna',      '39567890', DATE '1996-06-16', 'fluna@correo.test',      'Brown 76',         DATE '2023-09-01', NULL),
    (16, 'Bruno',    'Sosa',      '34678901', DATE '1989-12-01', 'bsosa@correo.test',      'Colón 1500',       DATE '2019-07-01', NULL),
    (17, 'Micaela',  'Herrera',   '37789012', DATE '1993-03-19', 'mherrera@correo.test',   'Güemes 250',       DATE '2020-02-10', NULL);

SELECT setval(pg_get_serial_sequence('personas', 'id_persona'), (SELECT MAX(id_persona) FROM personas));

INSERT INTO clientes (id_cliente, plan) VALUES
    (1, 'PREMIUM'), (2, 'BASICO'), (3, 'ESTANDAR'), (4, 'ESTANDAR'), (5, 'BASICO'), (6, 'PREMIUM'),
    (7, 'BASICO'), (8, 'ESTANDAR'), (9, 'PREMIUM'), (10, 'BASICO'), (11, 'ESTANDAR'), (12, 'PREMIUM');

INSERT INTO entrenadores (id_entrenador, modalidad) VALUES
    (13, 'GENERAL'), (14, 'PERSONAL'), (15, 'GENERAL'), (16, 'PERSONAL'), (17, 'GENERAL');

INSERT INTO es_jefe (id_entrenador, jefe) VALUES
    (13, 16), (14, 16), (15, 17), (17, 9);

INSERT INTO areas (nombre) VALUES ('Musculación'), ('Funcional'), ('Pileta'), ('Spinning');

INSERT INTO clases (tipo, dia, horario, area, entrenador) VALUES
    ('Funcional',    'LUNES',     TIME '08:00', 2, 13),
    ('Funcional',    'MIERCOLES', TIME '08:00', 2, 13),
    ('Spinning',     'MARTES',    TIME '19:00', 4, 15),
    ('Spinning',     'JUEVES',    TIME '19:00', 4, 15),
    ('Natación',     'LUNES',     TIME '18:00', 3, 17),
    ('Natación',     'VIERNES',   TIME '18:00', 3, 17),
    ('Musculación',  'MARTES',    TIME '10:00', 1, 14),
    ('Musculación',  'JUEVES',    TIME '10:00', 1, 16);

INSERT INTO reciben (clase, cliente) VALUES
    (1, 1), (1, 3), (1, 6), (2, 1), (2, 4), (3, 2), (3, 9), (3, 11), (4, 9), (5, 5),
    (5, 7), (5, 12), (6, 12), (7, 6), (7, 8), (8, 10), (8, 1);

INSERT INTO titulos (id_titulo, tipo, entrenador) VALUES
    (1, 'PERSONAL TRAINER', 13), (2, 'LICENCIADO EN MUSCULACION', 14),
    (3, 'PROFESORADO DE EDUCACION FISICA', 15), (4, 'CURSOS FITNESS', 15),
    (5, 'PROFESORADO DE EDUCACION FISICA', 16), (5, 'PERSONAL TRAINER', 17);

INSERT INTO jornadas_laborales (id_jornada, dia, hora_inicio, hora_fin, empleado) VALUES
    (1, 'LUNES',     TIME '07:00', TIME '13:00', 13),
    (2, 'MIERCOLES', TIME '07:00', TIME '13:00', 13),
    (3, 'MARTES',    TIME '09:00', TIME '15:00', 14),
    (4, 'MARTES',    TIME '16:00', TIME '22:00', 15),
    (5, 'JUEVES',    TIME '22:00', TIME '16:00', 15),
    (6, 'LUNES',     TIME '14:00', TIME '20:00', 17),
    (7, 'JUEVES',    TIME '08:00', TIME '14:00', 16),
    (8, 'VIERNES',   TIME '14:00', TIME '20:00', 17);

INSERT INTO pagos_clientes (fecha, monto, cliente) VALUES
    (DATE '2026-03-01', 45000, 1), (DATE '2026-04-01', 45000, 1), (DATE '2026-03-03', 25000, 2),
    (DATE '2026-03-05', 35000, 3), (DATE '2026-03-05', 35000, 4), (DATE '2026-04-02', 35000, 4),
    (DATE '2026-03-10', 45000, 6), (DATE '2026-03-12', 25000, 7), (DATE '2026-03-15', 35000, 8),
    (DATE '2026-03-01', 45000, 9), (DATE '2026-04-01', 45000, 9), (DATE '2026-03-20', 25000, 10),
    (DATE '2026-03-22', 35000, 11), (DATE '2026-03-02', 45000, 12),
    (DATE '2026-03-04', 25000, 5);
